### PR TITLE
Dev 6

### LINKED ISSUE #6: Add Edit and Delete Button and Refractor
*User Story: As a user, I can edit individual task, change name or description of the task or mark if the task is done or not.In addition, I can delete the task whether it is done or not*
- [x] **Add Edit Button and Delete Button (1h) 2h**
- [x] **Add Business Logic and route Logic concerning with edit and delete(1h) 2h**
- [ ] **Probably need to refractory by slicing if some logic might be used by other components(1h)**
- [ ] **Add gitignore, configure session, add static file **

### PR DESCRIPTION
**Pull request by viettrung2103**
User Story: As a user, I can edit individual task, change name or description of the task or mark if the task is done or not.In addition, I can delete the task whether it is done or not

 Add Edit Button and Delete Button (1h) 2h
 Add Business Logic and route Logic concerning with edit and delete(1h) 2h
 Probably need to refractory by slicing if some logic might be used by other components(1h)
 **Add gitignore, configure session, add static file **

### CODE REVIEW

**Comment by stenvma81** [comment]
PR looks ok, but could use a short description on what was done. As you can see, explaining the purpose on the the first comment can make the commits sit better in the mix. If nothing else, you can add "Closes #6" to the PR to make it immediately clear how it is related to the issues.

Other comments posted under the issue -->

**Comment by baldez300** [comment]
**README.md:**

Since I didn't see **README.md** file yet for this project, could you share your plan on what information you intend to include?

**Commits:**

The commit messages are concise, but could you provide a bit more detail on what each update entails?
For example, what changes were made to the requirements.txt file?

**src/app.py:**

The code is well-structured. Can you explain the decision to use Flask for this project?

**src/schema.sql:**

In the CREATE TABLE statement, there seems to be a mismatch between "task_id" and "id." Could you clarify this discrepancy?

**src/templates/lists/edit_list.html:**

In the checkbox input for "is_done," you use` {{ "checked" if task.is_done == 1 else "" }}`. Can you explain the reasoning behind this approach?
Are there any validations or error handling mechanisms in place for the form submission?

**src/templates/lists/lists.html:**

Is there any specific reason for using a hidden input for "task_id" in the forms? (`<input name="task_id" type="hidden" value="{{task.task_id}}">`)

**src/templates/login.html:**

Is there a specific reason for turning off autocomplete for the username input? (`<input type="text" autocomplete="off" required autofocus name="name" placeholder="Name">`)
These questions aim to provide a deeper understanding of the code, its rationale, and potential areas of improvement.

**Comment by viettrung2103** [comment]
@stenvma81 
Thank you for the reminds. I should add some comment when I first open this PR so that other will understand what is the purpose of this PR. At first, I thought when I link to the Issues, it should automatically show the here in PR comment.
About the atomic commit, I think that my commit is over atomic. As I should add more detail to my commit, like to what the new commit affect or how it will affect the overall structure or program

**Comment by viettrung2103** [comment]
@baldez300 
1. I plan to create a Todo App using Flask for myself.
2. I was introduced to Flasked during my class and I would like to learn more about it. That why I use this chance to both have a project of  my own and learning Flask too.
3. Thank you for pointing that out. it should be task_id like you said.
4. First, about the validation, I do not have any validation for the backend, only the in frontend where some field has to be field in order to submit the form, like in the login form.
Second, this statement means if the task is done, which is_done = 1, then it will return "checked". In HTML, to display whether the checkbox input is checked or not is throught this keyword.
5 This is a seperate form beside edit form. There is a delete form with the input is the id of that current task. However, I do not want to display the id of the current task again. I mark it as hidden.
6. I set the autocomplete to off as I want the user to type manually his name into the logic field. It will make the user less lazy. It is just my personal taste of UX

**Pull request merged**
